---
- name: kibana package
  become: yes
  apt:
    name: kibana
    state: present

- name: kibana configuration file
  become: yes
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: kibana service
  become: yes
  service:
    name: kibana
    state: started
    enabled: yes
...
