---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - setup:
        gather_subset: hardware
  vars:
    kube_env_artifact_dir: /vagrant_data/kubernetes
    accessible_ip_prefix: "10.11"
    pod_network_cidr: "10.12.0.0/24"
  roles:
    - common
    - docker-ce
    - k8s-common
    - k8s-init
...
